CREATE TABLE hlv (
  id INT AUTO_INCREMENT PRIMARY KEY,
  RequestedBy VARCHAR(50) NOT NULL,
  ItemName VARCHAR(50) NOT NULL,
  Quantity VARCHAR(50) NOT NULL,
  ItemRecipient VARCHAR(50) NOT NULL,
  RequestDate VARCHAR(50) NOT NULL,
  Status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;
